# Julia: Quick Reference

#### Excerpt from *Learn Julia in Y Minutes* (https://learnxinyminutes.com/docs/julia/), adapted by M. Giugliano

#### Textual comments
Comments are lines of text ignored by the language interpreter and used to add readability to the code.

In [1]:
# Single line comments start with a hash (pound) symbol.

# Whatever follows the hash symbol is ignored by the computer
# but it does help a bit documenting and explaining the code to humans!

#= Multiline comments can be written
   by putting '#=' before the text  and '=#'
   after the text. They can also be nested.
=#

#####

# Note: Julia is case-sensitive. It matters if you write lower case or upper case
# as they are NOT considered by the computer to be the same letters!!

#### 1. Primitive data types and operators
For our sake, numerical computing is all about numbers, variables, and functions that operates on variables.

In [2]:
# Everything in Julia is an expression, meaning it returns some "value" 
# This is usually visualised on screen upon evaluation, but it can be suppressed 
# by simply terminating the line with a semicolumn symbol (;)

# There are several basic types of numbers: among them integers and floating point numbers

3               # => 3 (Int64)         (integer, 64 bit resolution)
3.2             # => 3.2 (Float64)     (floating point, 64 bit resolution)

3.2

In [3]:
# All of the normal infix arithmetic operators are available: it is like having calculator... on steroids!

1 + 1      # => 2
8 - 1      # => 7
10 * 2     # => 20
35 / 5     # => 7.0
5 / 2      # => 2.5   Remember: dividing an Int by an Int always results in a Float
div(5, 2)  # => 2     For a truncated result, use the function div (i.e. integer division)
2 ^ 2      # => 4     power
12 % 10    # => 2   (reminder of an integer division)

2

In [4]:
# Enforce precedence in the arithmetic evaluations with parentheses

(1 + 3) * 2 # => 8

8

In [5]:
# Boolean values are also primitives

true
false

# Boolean operators

!true  # => false
!false # => true
1 == 1 # => true
2 == 1 # => false
1 != 1 # => false
2 != 1 # => true
1 < 10 # => true
1 > 10 # => false
2 <= 2 # => true
2 >= 2 # => true

# Comparisons can be chained
1 < 2 < 3 # => true
2 < 3 < 2 # => false

false

In [6]:
# Strings are created with the symbol "
"This is a string."


"This is a string."

In [7]:
# Printing strings on screen is very easy

println("I'm Julia. Nice to meet you!")

I'm Julia. Nice to meet you!


In [8]:
# The symbol $ can be used for string "interpolation":
println("2 + 2 = $(2 + 2)") # => "2 + 2 = 4"

# You can put any Julia expression inside the parentheses and it will be evaluated 
# and transformed into the corresponding equivalent string characters

# String can also be compared lexicographically
"good" > "bye"    # => true
"good" == "good"  # => true
"1 + 2 = 3" == "1 + 2 = $(1+2)" # => true

2 + 2 = 4


true

#### 2. Variables and Arrays
Remember the concept of having a box or a bin where you place an element for further use?

In [9]:
# You don't declare (scalar) variables before assigning to them some (numerical) value.
some_var = 5    # => 5
some_var        # => 5

5

In [10]:
# You can of course also assing a single character to a variable 
favourite_letter = 'm'

'm': ASCII/Unicode U+006d (category Ll: Letter, lowercase)

In [11]:
# If you try accessing a previously unassigned variable, you get an error
# Please don't be afraid of getting errors and ..read therein why the system might complain

some_other_var   # => ERROR: some_other_var not defined

LoadError: UndefVarError: some_other_var not defined

In [12]:
# Variable names start with a letter or underscore.
# After that, you can if you want use letters, digits, underscores, and exclamation points.

SomeOther9_Var123 = 6 # => 6

# You can also use fancy "unicode" characters, if you want
☃ = 8 # => 8

# These might be handy for directly relating to mathematical notation 
2 * π # => 6.283185307179586      (note: π is pre-defined in Julia)

6.283185307179586

In [13]:
# 1-dimensional arrays (vectors) can be used to store a sequence of values (of same type!)
# They can be initialised as empty collections (e.g. Int64)
a = Float64[]    # => 0-element Int64 Array

# or, explicitly, indicating every single element, with comma-separated values.
b = [4.1, 5, 6]    # => 3-element Int64 Array: [4.1, 5, 6]
b = [4.1; 5; 6]    # => 3-element Int64 Array: [4.1, 5, 6]

# They are "indexed" by integers 1 through n, so that individual elements can be accessed
# and manipulated as any other scalar variables.
b[1]    # => 4.1   Remember: in Julia indexes start from 1, not 0!
b[2]    # => 5
b[end]  # => 6     "end" is a shorthand for the last index. 
b[end-1] # => 5    Between [ ] you can place any expression that returns an integer!

# Of course you can replace individual elements of the vector
b[1]=21

# You can type the following command to get the length of a specific array
length(b)    #  => 3

# and you if simply type the name of the variable, you will get its content displayed
b

# Have you noticed it? Commands (or existing **functions** uses the round parentheses)
# While referring to an element of an array requires using the square brackets!

3-element Array{Float64,1}:
 21.0
  5.0
  6.0

In [14]:
# Add stuff to the end of a list with the commands push! and append!
# Sometimes, in fact, you might not know in advance the size of the array you are managing
push!(a,1)     # => [1]        "a" was indeed empty, when created
push!(a,2)     # => [1,2]
push!(a,4)     # => [1,2,4]
push!(a,3)     # => [1,2,4,3]
append!(a,b)   # => [1,2,4,3,21,5,6]

# Remove from the end with pop
pop!(b)        # => 6 and b is now [21,5]

# Let's put it back
push!(b,6)   # b is now [21,5,6] again.

# Function names that end in exclamations points indicate that they modify permanently 
# their argument. Otherwise functions usually return an output (i.e. an expression evaluated)

arr = [5,4,6] # => 3-element Int64 Array: [5,4,6]
sorted_array = sort(arr)     # => [4,5,6]; arr is still [5,4,6], but sorted_array is [4,5,6]
sort!(arr)    # => [4,5,6]; arr has been sorted now [4,5,6]

3-element Array{Int64,1}:
 4
 5
 6

In [15]:
# Any attempt at referring to an element of an array outside the allowed boundaries
# returns an error. Don't be afraid of this!
# Errors list the line where the problem occurred and sometimes you can get useful info.
arr[5]

LoadError: BoundsError: attempt to access 3-element Array{Int64,1} at index [5]

In [16]:
# You can initialize arrays also specifying a range of values
a = [1:5;] # => 5-element Int64 Array: [1,2,3,4,5]

# even with a non-unitary increment
aa = [2:2:10;] # => 5-element Int64 Array: [2,4,6,8,10]
bb = [1:2:10;] # => 5-element Int64 Array: [1,3,5,7,9]

# You can look at ranges with such a "slice" syntax.
a[1:3] # => [1, 2, 3]
bb[2:end] # => [3, 5, 7, 9]

# Finally, you can check for existence of an element in a list with in
in(7, bb) # => true


true

In [17]:
# 2-dimensional arrays use space-separated values and semicolon-separated rows.
mymatrix = [1 2 3; 4 5 6] # => 2x3 Int64 Array: [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [18]:
# Elements of 2-dimensional array can be addressed by specifying two indexes
mymatrix[2,1]    # => 4   (row 2, column 1)

# and can be similarly sliced
mymatrix[1:2,2] # => [2, 5]   (fixing column 2, all the rows ranging from 1 to 2)

2-element Array{Int64,1}:
 2
 5

In [19]:
# 1- and 2-dimensional arrays can be also filled with default values

myzeros_array = zeros(Float64,4) # => [0.0, 0.0, 0.0, 0.0]
myones_array = ones(Float64,4)   # => [1.0, 1.0, 1.0, 1.0]
 
myzero_matrix = zeros(Float64,4,3) # 4x3 Float64 Array: [0 0 0; 0 0 0; 0 0 0; 0 0 0]

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [20]:
# One can also fill an array with random numbers, drawn from a Gaussian (normal) distribution
# with zero mean and unitary variance

myrandom_array1 = randn(Float64,8)

8-element Array{Float64,1}:
  1.77502  
  0.309366 
 -1.45378  
  0.0663759
 -0.467656 
 -0.918256 
 -1.16307  
 -0.670127 

In [21]:
# or a uniform distribution between 0 and 1

myrandom_array2 = rand(Float64,5)

5-element Array{Float64,1}:
 0.140802
 0.767896
 0.672675
 0.303776
 0.392174

In [22]:
# Mean and standard deviation can be easily computer
myrandom_array1 = randn(Float64,10000);   # Note: I placed here the ";", suppressing display!
myrandom_array2 = rand(Float64, 10000);  # Note: I placed here the ";", suppressing display!

m1 = mean(myrandom_array1)
println("The mean of 10000 gaussian samples is $(m1) (0 in theory)\n")

s1 = std(myrandom_array1)
println("The standard deviation of 10000 gaussian samples is $(s1) (1 in theory)\n")

m2 = mean(myrandom_array2)
println("The mean of 10000 uniform samples is $(m2) (0.5 in theory)\n")

The mean of 10000 gaussian samples is -0.00531767001237156 (0 in theory)

The standard deviation of 10000 gaussian samples is 1.0018066788211912 (1 in theory)

The mean of 10000 uniform samples is 0.49893860887699565 (0.5 in theory)



#### 3. Controlling the flow of a program
IKEA furniture sometimes gets interesting when they tell you *"go to page 4, if your closet does not have sliding mirror doors, otherwise continue reading*".

In [23]:
# Let's create a variable and assign a numerical value to it
some_var = 5

# Here is an if-then-else statement. Indentation is not meaningful in Julia.
if some_var > 10
    println("some_var is totally bigger than 10.")
elseif some_var < 10    # This elseif clause is optional.
    println("some_var is smaller than 10.")
else                    # The else clause is optional too.
    println("some_var is indeed 10.")
end
# => prints "some var is smaller than 10"

some_var is smaller than 10.


In [24]:
# For loops are used to iterate over the content of an array for instance

arr = randn(Float64, 10)
n   = length(arr)
m   = 0.

for i=1:n
    m = m + arr[i]
end

println("The mean of $(n) gaussian samples is $(m/n) (0. in theory)\n")

The mean of 10 gaussian samples is -0.27989005313763515 (0. in theory)



In [25]:
# The above code could have of course been written equivalently as

m   = 0.
m   = m + arr[1]
m   = m + arr[2]
m   = m + arr[3]
m   = m + arr[4]
m   = m + arr[5]
m   = m + arr[6]
m   = m + arr[7]
m   = m + arr[8]
m   = m + arr[9]
m   = m + arr[10]       # Here there are as many lines as elements in arr
                        # Imagine having 500000 elements. 

println("The mean of $(n) gaussian samples is $(m/n) (0. in theory)\n")

The mean of 10 gaussian samples is -0.27989005313763515 (0. in theory)



In [26]:
# Or even as

m = arr[1] + arr[2] + arr[3] + arr[4] + arr[5] + arr[6] + arr[7] + arr[8] + arr[9] + arr[10]
# Here the line is as long as there are elements in arr. Imagine having 500000 elements.
println("The mean of $(n) gaussian samples is $(m/n) (0. in theory)\n")

The mean of 10 gaussian samples is -0.27989005313763515 (0. in theory)



In [27]:
# You might not know in advance how many times a loop has to be repeated

x = 0
while x < 4
    println(x)
    x += 1  # Shorthand for x = x + 1
end

0
1
2
3


#### 4. Functions (i.e. new commands that become available to the user)
In Julia, whatever code you place inside a function becomes incredibly fast to execute compared to every time having one instruction after the other.

In [28]:
# The keyword 'function' creates new functions
#function name(arglist)
#  body...
#end
function add(x, y)
    println("x is $x and y is $y")

    # Functions return the value of their last statement
    x + y
end

add(5, 6) # => 11 after printing out "x is 5 and y is 6"

x is 5 and y is 6


11

You can get a lot more detail from The Julia Manual  http://docs.julialang.org/en/latest/manual/ .

The best place to get help with Julia is the (very friendly) mailing list
https://groups.google.com/forum/#!forum/julia-users .